//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetFactura
    {
        public int IDDetFactura { get; set; }
        public string Cantidad { get; set; }
        public string SubTotal { get; set; }
        public string Total { get; set; }
        public string Estado { get; set; }
        public int IDArticulos { get; set; }
        public int IDFactura { get; set; }
        public int IDUsuario { get; set; }
    
        public virtual tblArticulo tblArticulo { get; set; }
        public virtual tblFactura tblFactura { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
